"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

limit = 4e6
fibonacci = [1, 2]
while fibonacci[-1] < limit:
  next = fibonacci[-1] + fibonacci[-2]
  fibonacci.append(next)

suma = 0
i = 0
while i < len(fibonacci):
  if fibonacci[i] % 2 == 0:
    suma = suma + fibonacci[i]
    i += 1
  else:
    i += 1

print("La suma de los términos pares de la sucesión de Fibonacci menores a 4 millones es {0}".format(suma))
